In [1]:
# Welcome to your new notebook
# Type here in the cell editor to add code!
import pyspark.pandas as pd

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 3, Finished, Available, Finished)

/opt/spark/python/lib/pyspark.zip/pyspark/pandas/__init__.py:50: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.

In [2]:
silver_actual=pd.read_delta("abfss://eb257234-8b24-4c02-8b7c-53b230c8bb1a@onelake.dfs.fabric.microsoft.com/fd0e410a-d046-4650-86ee-197dcd0650f1/Tables/dbo/silver_actual")

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 4, Finished, Available, Finished)

/opt/spark/python/lib/pyspark.zip/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_delta`, the default index is attached which can cause additional overhead.

In [4]:
silver_actual.head()

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 6, Finished, Available, Finished)

   year quarter month    sku_code                                      sku_description    category sub_category     product sub_product cluster_head       channel location  volume_mt  gross_sales  discount  trade_spend  total_t_and_disc  net_revenue  raw_material  packging_material  industrial_fixed_cost  industrial_variable_cost  total_fixed_and_variable_cost    cogs  goss_profit   gp%  marketing  sandd  ganda  other_inc_and_exp  ebitda  depriciation  one_off_item  tax  interest_income  interest_exp  net_profit
0  2024      Q1   jan  5006810853                       HEINZ 3 PEPPER MAYO - 12X400ML      others        Heinz       Rusks  Brown Rusk      Shreyas  Online Sales      Mah       0.03       262.03       0.0         0.00              0.00       262.03       -202.64                0.0                    0.0                       0.0                            0.0 -202.64        59.39  0.23       0.05 -19.30  -2.50                0.0   37.64         -0.78         -0.37  0.0              0.0         -0.35       36.14
1  2021      Q3   jul  5006410592  Crunchy FRUIT COCKTAIL, CHOICE IN SYRUP 24X425G EOE  Fresh Fare         Foul  Foul Plain  Foul Plain      Shreyas  Direct Sales      Mah       0.02        55.62       0.0         0.00              0.00        55.62        -45.18                0.0                    0.0                       0.0                            0.0  -45.18        10.44  0.19       0.01  -4.10  -0.53                0.0    5.82         -0.17         -0.08  0.0              0.0         -0.08        5.50
2  2024      Q2   jun  5006413084    CG TUNA SALATA MEXICAN RECIPE 2X24X160G EASY PEEL  Fresh Fare         Foul  Foul Plain  Foul Plain      Shreyas  Direct Sales      Mah       0.01       100.00       0.0       -11.69            -11.69        88.31        -72.28                0.0                    0.0                       0.0                            0.0  -72.28        16.03  0.18       0.02  -6.50  -0.84                0.0    8.70         -0.26         -0.13  0.0              0.0         -0.12        8.19
3  2022      Q2   apr  4040474957      Crunchy 400g 24T Baked Beans in T/S EOE-(Int`l)  Fresh Fare         Foul  Foul Plain  Foul Plain      Shreyas  Online Sales      Mah       0.01        15.69       0.0        -1.57             -1.57        14.12         -9.68                0.0                    0.0                       0.0                            0.0   -9.68         4.44  0.31       0.00  -1.04  -0.13                0.0    3.27         -0.04         -0.02  0.0              0.0         -0.02        3.19
4  2021      Q1   jan  4040444005                      MZ 400g 24T Red Kidney Beans NL  Fresh Fare         Foul  Foul Plain  Foul Plain      Shreyas  Direct Sales      Mah       0.01         8.95       0.0        -1.27             -1.27         7.68         -9.37                0.0                    0.0                       0.0                            0.0   -9.37        -1.69 -0.22       0.00  -0.57  -0.07                0.0   -2.33         -0.02         -0.01  0.0              0.0         -0.02       -2.38

In [5]:
gold_fact_actual = pd.read_delta("abfss://eb257234-8b24-4c02-8b7c-53b230c8bb1a@onelake.dfs.fabric.microsoft.com/fd0e410a-d046-4650-86ee-197dcd0650f1/Tables/dbo/gold_fact_actual")

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 7, Finished, Available, Finished)

/opt/spark/python/lib/pyspark.zip/pyspark/pandas/utils.py:1016: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_delta`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

In [6]:
gold_fact_actual.head()

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 8, Finished, Available, Finished)

   product_key  Date_id  cluster_id  channel_id  location_id  volume_mt  gross_sales  discount  trade_spend  total_t_and_disc  net_revenue  raw_material  packging_material  industrial_fixed_cost  industrial_variable_cost  total_fixed_and_variable_cost     cogs  goss_profit   gp%  marketing  sandd  ganda  other_inc_and_exp   ebitda  depriciation  one_off_item  tax  interest_income  interest_exp  net_profit
0          618       12           6           0            6       0.05       277.77       0.0      -152.77           -152.77       125.00       -235.93                0.0                    0.0                   -421.85                        -421.85  -657.77      -532.77 -4.26       0.02  -9.21  -1.19                0.0  -543.15         -0.37         -0.18  0.0              0.0         -1.13     -544.83
1         1279        5           6           0            6       0.11       718.93       0.0       -65.36            -65.36       653.58       -559.45                0.0                    0.0                  -1091.84                       -1091.84 -1651.29      -997.71 -1.53       0.12 -48.14  -6.24                0.0 -1051.97         -1.94         -0.93  0.0              0.0         -2.83    -1057.67
2         1306       33           6           5            6      -0.01       -60.16       0.0         1.82              1.82       -58.34         47.12                0.0                    0.0                     91.37                          91.37   138.49        80.15 -1.37      -0.01   4.30   0.56                0.0    84.99          0.17          0.08  0.0              0.0          0.24       85.48
3         2495       35           6           5            6      -0.01       -43.83       0.0         3.30              3.30       -40.53         30.98                0.0                    0.0                     66.56                          66.56    97.54        57.01 -1.41      -0.01   2.99   0.39                0.0    60.37          0.12          0.06  0.0              0.0          0.17       60.72
4         1306       54           6           5            6      -0.01       -83.33       0.0        11.69             11.69       -71.64         65.26                0.0                    0.0                    126.55                         126.55   191.81       120.17 -1.68      -0.01   5.28   0.68                0.0   126.12          0.21          0.10  0.0              0.0          0.33      126.76

In [10]:
print(silver_actual.shape)
print(gold_fact_actual.shape)

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 12, Finished, Available, Finished)

(477872, 37)
(477872, 30)

In [18]:
print("silver actual",silver_actual['gross_sales'].sum())
print("fact gold actual",gold_fact_actual['gross_sales'].sum())

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 20, Finished, Available, Finished)

silver actual 673746327.1789787
fact gold actual 673746327.1789917

In [19]:
print("silver net_revenue", silver_actual['net_revenue'].sum())
print("gold net_revenue", gold_fact_actual['net_revenue'].sum())

print("silver net_profit", silver_actual['net_profit'].sum())
print("gold net_profit", gold_fact_actual['net_profit'].sum())

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 21, Finished, Available, Finished)

silver net_revenue 560069105.8152264
gold net_revenue 560069105.8151819
silver net_profit 61125383.38247627
gold net_profit 61125383.382477

In [23]:
print("null product_key",
      gold_fact_actual['product_key'].isna().sum())

print("null channel_key",
      gold_fact_actual['channel_id'].isna().sum())

print("null date_id",
      gold_fact_actual['Date_id'].isna().sum())

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 25, Finished, Available, Finished)

null product_key 0
null channel_key 0
null date_id 0

In [26]:
assert round(silver_actual['gross_sales'].sum()) == round(gold_fact_actual['gross_sales'].sum()), \
    "Gross sales mismatch!"

assert gold_fact_actual['product_key'].isna().sum() == 0, \
    "Null product_key found!"

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 28, Finished, Available, Finished)

In [25]:
print("silver actual",round(silver_actual['gross_sales'].sum()))

StatementMeta(, 3d1652cc-d5c8-4e37-b6c0-532345f7cb00, 27, Finished, Available, Finished)

silver actual 673746327